const env=process.env;
import { taskIdentity as identity } from '../../task-access';
import { validateValues } from '../../task-model';
import {sheetsBridge as bridge} from '../../sheets-bridge';
import {parseTaskDate} from '../../date-model';
import {latestSnapshot,storeSnapshot} from '../../live-snapshot';
import {isSnapshot} from '../../sync-model';
export const dynamic = 'force-dynamic';
function config() { const e=env as unknown as Record<string,string>; return {url:e.SHEETS_BRIDGE_URL,key:e.SHEETS_BRIDGE_KEY,editors:(e.EDITOR_EMAILS||'').toLowerCase().split(',').map(s=>s.trim()).filter(Boolean)}; }
function json(body:unknown,status=200){return Response.json(body,{status,headers:{'Cache-Control':'no-store, private','Vary':'Cookie'}})}
export async function GET(){const who=await identity();if(!config().url||!config().key)return json({...who,connected:false,tasks:null});try{const snapshot=await latestSnapshot();const fresh=Date.now()-Date.parse(snapshot.checkedAt)<120000;return json({...snapshot,...who,connected:fresh,error:fresh?undefined:'ข้อมูลอาจยังไม่ล่าสุด กำลังเชื่อมต่อกับชีตอีกครั้ง'})}catch{return json({...who,connected:false,error:'เชื่อมต่อ Google Sheets ไม่สำเร็จ ข้อมูลที่แสดงอาจยังไม่ล่าสุด'},503)}}
export async function POST(request:Request){const who=await identity();if(!who.canEdit)return json({error:'บัญชีนี้ไม่มีสิทธิ์แก้ไขงาน'},403);if(request.headers.get('Origin')!==new URL(request.url).origin)return json({error:'คำขอไม่ถูกต้อง'},403);if(!request.headers.get('Content-Type')?.includes('application/json'))return json({error:'รูปแบบคำขอไม่ถูกต้อง'},415);try{const bodyText=await request.text();if(bodyText.length>65000)return json({error:'ข้อมูลยาวเกินไป'},413);const body=JSON.parse(bodyText);const values=validateValues(body.values);if(body.startDate!==undefined){if(typeof body.startDate!=='string'||body.startDate.length>50||(body.startDate&&!parseTaskDate(body.startDate)))return json({error:'วันเริ่มงานไม่ถูกต้อง'},400);const start=parseTaskDate(body.startDate),end=parseTaskDate(values[6]);if(start&&end&&start>end)return json({error:'กำหนดส่งต้องไม่อยู่ก่อนวันเริ่มงาน'},400);}if(!['create','update'].includes(body.action)||typeof body.requestId!=='string'||! /^[a-zA-Z0-9-]{16,64}$/.test(body.requestId))return json({error:'ข้อมูลไม่ถูกต้อง'},400);if(body.action==='update'&&(typeof body.version!=='string'||!values[0]))return json({error:'ไม่พบข้อมูลต้นฉบับ'},400);const result=await bridge({action:body.action,values,startDate:body.startDate,version:body.version,requestId:body.requestId});if(isSnapshot(result)){try{await storeSnapshot(result)}catch{console.error('Snapshot cache update failed after successful save');}}return json({...result,connected:true});}catch(error){const msg=error instanceof Error?error.message:'';if(msg==='CONFLICT')return json({error:'งานนี้ถูกแก้ไขแล้ว กรุณาปิดฟอร์มแล้วเปิดใหม่เพื่อใช้ข้อมูลล่าสุด'},409);if(msg==='NOT_CONFIGURED')return json({error:'ยังไม่ได้เชื่อมต่อ Google Sheets'},503);return json({error:'บันทึกไม่สำเร็จ โปรดตรวจข้อมูลและลองอีกครั้ง หากการเชื่อมต่อขาดหายให้ตรวจรายการก่อนบันทึกซ้ำ'},502)}}
