// Deploy as a Web app, execute as owner. Store BRIDGE_KEY in Script Properties.
// Every request requires the server-held key. Never put it in frontend code.
const SHEET_ID='1-g0Px1bxaeeNbbom9ZsNL0mCWlgfr3qBXHxcswMq6QU';
const TAB='ตารางงาน';
function setup(){const p=PropertiesService.getScriptProperties();if(!p.getProperty('BRIDGE_KEY'))p.setProperty('BRIDGE_KEY',Utilities.getUuid()+Utilities.getUuid());SpreadsheetApp.openById(SHEET_ID).getSheetByName(TAB).getRange('A1').getValue();}
function doPost(e){let lock;try{const p=JSON.parse(e.postData.contents);const expected=PropertiesService.getScriptProperties().getProperty('BRIDGE_KEY');if(!expected||p.key!==expected)return output({ok:false,error:'UNAUTHORIZED'});lock=LockService.getScriptLock();lock.waitLock(20000);if(p.action==='upload')return output(uploadFile(p));const sheet=SpreadsheetApp.openById(SHEET_ID).getSheetByName(TAB);if(!sheet)throw Error('MISSING_TAB');if(p.action==='read')return output(makeSnapshot(sheet));if(!['create','update'].includes(p.action))throw Error('INVALID');validate(p.values);if(p.startDate!==undefined&&(typeof p.startDate!=='string'||p.startDate.length>50))throw Error('INVALID');if(!/^[a-zA-Z0-9-]{16,64}$/.test(p.requestId||''))throw Error('INVALID');const props=PropertiesService.getScriptProperties();const requestKey='request_'+p.requestId;if(props.getProperty(requestKey))return output(makeSnapshot(sheet));
const tasks=readTasks(sheet);let row;let previous;
if(p.action==='update'){const matches=tasks.filter(t=>t.values[0]===p.values[0]);if(matches.length!==1||matches[0].version!==p.version)throw Error('CONFLICT');previous=matches[0];row=previous.row;}else{const all=sheet.getRange(2,1,Math.max(1,sheet.getLastRow()-1),11).getDisplayValues();const free=all.findIndex(r=>r.slice(1).every(v=>!v));row=free<0?sheet.getLastRow()+1:free+2;const reserved=all.map(r=>Number(r[0])).filter(Number.isFinite);p.values[0]=all[row-2]&&all[row-2][0]||String(Math.max(0,...reserved)+1);if(row>sheet.getMaxRows())sheet.insertRowsAfter(sheet.getMaxRows(),1);}
// Only changed cells are written: existing smart chips, formulas, dates and formatting survive.
for(let col=0;col<10;col++){if(previous&&p.values[col]===previous.values[col])continue;sheet.getRange(row,col+1).setValue(literal(p.values[col]));}
if(p.startDate!==undefined)sheet.getRange(row,12).setValue(p.startDate?"'"+p.startDate:'');
const today=Utilities.formatDate(new Date(),'Asia/Bangkok','dd/MM/yyyy').split('/');today[2]=String(Number(today[2])+543);sheet.getRange(row,11).setValue("'"+today.join('/'));SpreadsheetApp.flush();props.setProperty(requestKey,String(Date.now()));const saved=props.getProperties();Object.keys(saved).filter(k=>k.startsWith('request_')&&Number(saved[k])<Date.now()-86400000).forEach(k=>props.deleteProperty(k));return output(sendSnapshot(makeSnapshot(sheet)));
}catch(err){return output({ok:false,error:err.message==='CONFLICT'?'CONFLICT':'FAILED'});}finally{if(lock&&lock.hasLock())lock.releaseLock();}}
function readTasks(sheet){const count=Math.max(sheet.getLastRow()-1,0);if(!count)return [];const range=sheet.getRange(2,1,count,11),values=range.getDisplayValues(),links=range.getRichTextValues(),starts=sheet.getRange(2,12,count,1).getDisplayValues();return values.map((r,i)=>{let pdfUrl=links[i][9]&&links[i][9].getLinkUrl();if(!pdfUrl&&r[0]==='12'&&r[9]==='ใบส่งรายชื่อรวมทุกกีฬา.pdf')pdfUrl='https://drive.google.com/file/d/1cqrnPnbg2MU0WkKxUZBltKWXcwW-gyVC/view';const version=Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,JSON.stringify(starts[i][0]?[...r,starts[i][0]]:r)));return {row:i+2,values:r,startDate:starts[i][0]||'',version,pdfUrl:pdfUrl||null};}).filter(t=>t.values[1]);}
function literal(v){return /^[=+@-]/.test(v)&&v!=='-'?"'"+v:v;}
function validate(v){if(!Array.isArray(v)||v.length!==11||!v.every(s=>typeof s==='string'&&s.length<=5000)||!v[1].trim()||v[1].length>300)throw Error('INVALID');const choices={2:['งาน','ไอเดีย','ปัญหา','อื่นๆ'],4:['','ยังไม่เริ่ม','กำลังดำเนินการ','ติดขัด','เสร็จแล้ว'],5:['','ต่ำ','ปกติ','สูง','ด่วน']};Object.keys(choices).forEach(k=>{if(!choices[k].includes(v[k]))throw Error('INVALID');});}
function output(value){return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);}
function prepareDrive(){setup();const sheet=SpreadsheetApp.openById(SHEET_ID).getSheetByName(TAB);const header=sheet.getRange(1,12).getDisplayValue();if(header&&header!=='วันเริ่มงาน')throw Error('COLUMN_IN_USE');if(!header)sheet.getRange(1,12).setValue('วันเริ่มงาน');const folder=uploadFolder();console.log('โฟลเดอร์ไฟล์แนบ: '+folder.getUrl());}
function uploadFolder(){const props=PropertiesService.getScriptProperties();const id=props.getProperty('UPLOAD_FOLDER_ID');if(id)return DriveApp.getFolderById(id);const folder=DriveApp.createFolder('ไฟล์แนบตารางงานคณะสุโขทัย');props.setProperty('UPLOAD_FOLDER_ID',folder.getId());return folder;}
function uploadFile(p){if(!/^[a-zA-Z0-9-]{16,80}$/.test(p.requestId||'')||!p.file||typeof p.file.data!=='string'||p.file.data.length>13981020||typeof p.file.name!=='string'||p.file.name.length>200||!['private','link'].includes(p.file.share))throw Error('INVALID');const props=PropertiesService.getScriptProperties();const saved=props.getProperty('upload_'+p.requestId);let file;if(saved){file=DriveApp.getFileById(saved);}else{const bytes=Utilities.base64Decode(p.file.data);if(bytes.length>10485760||!bytes.length)throw Error('INVALID');const name=p.file.name.replace(/[\/\r\n]/g,'_');const mime=/^[a-zA-Z0-9.+-]+\/[a-zA-Z0-9.+-]+$/.test(p.file.mime||'')?p.file.mime:'application/octet-stream';file=uploadFolder().createFile(Utilities.newBlob(bytes,mime,name));props.setProperty('upload_'+p.requestId,file.getId());}if(p.file.share==='link')file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);return {ok:true,url:file.getUrl(),name:file.getName(),id:file.getId()};}


function makeSnapshot(sheet){const props=PropertiesService.getScriptProperties();const tasks=readTasks(sheet);const revision=Math.max(Date.now(),Number(props.getProperty('SYNC_REVISION')||0)+1);props.setProperty('SYNC_REVISION',String(revision));return {ok:true,tasks,revision,checkedAt:new Date(revision).toISOString()};}
function sendSnapshot(snapshot){try{const p=PropertiesService.getScriptProperties();const url=p.getProperty('SYNC_WEBHOOK_URL');if(!url)return snapshot;const result=UrlFetchApp.fetch(url,{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+p.getProperty('BRIDGE_KEY')},payload:JSON.stringify(snapshot),muteHttpExceptions:true});if(result.getResponseCode()!==200)throw Error('HTTP '+result.getResponseCode());p.setProperty('SYNC_LAST_OK',String(Date.now()));p.deleteProperty('SYNC_LAST_ERROR');}catch(err){PropertiesService.getScriptProperties().setProperty('SYNC_LAST_ERROR',String(err.message));console.warn('Live update deferred; periodic refresh will recover.');}return snapshot;}
function pushSheetSnapshot(){const lock=LockService.getScriptLock();lock.waitLock(20000);try{return sendSnapshot(makeSnapshot(SpreadsheetApp.openById(SHEET_ID).getSheetByName(TAB)));}finally{lock.releaseLock();}}
function onTaskSheetEdit(e){if(e&&e.range&&e.range.getSheet().getName()===TAB)pushSheetSnapshot();}
function onTaskSheetChange(e){if(e&&e.changeType!=='EDIT')pushSheetSnapshot();}
function setupLiveUpdates(){const p=PropertiesService.getScriptProperties();if(!p.getProperty('SYNC_WEBHOOK_URL'))throw Error('Set SYNC_WEBHOOK_URL in Script Properties first');const triggers=ScriptApp.getProjectTriggers();if(!triggers.some(t=>t.getHandlerFunction()==='onTaskSheetEdit'))ScriptApp.newTrigger('onTaskSheetEdit').forSpreadsheet(SHEET_ID).onEdit().create();if(!triggers.some(t=>t.getHandlerFunction()==='onTaskSheetChange'))ScriptApp.newTrigger('onTaskSheetChange').forSpreadsheet(SHEET_ID).onChange().create();pushSheetSnapshot();if(p.getProperty('SYNC_LAST_ERROR'))throw Error(p.getProperty('SYNC_LAST_ERROR'));console.log('Live sheet updates enabled; initial snapshot delivered.');}

function authorizeLiveConnection(){ const url=PropertiesService.getScriptProperties().getProperty('SYNC_WEBHOOK_URL'); if(!url)throw Error('Set SYNC_WEBHOOK_URL first'); UrlFetchApp.fetch(url,{muteHttpExceptions:true}); setupLiveUpdates(); }
